package com.ssimo.papere

const val MIN_RESOLUTION = 2000

val CATEGORIES = mapOf(
    "checkbox_space" to listOf(
        "Category:Featured pictures of astronomy",
        "Category:Featured pictures of space exploration"
    ),
    "checkbox_objects" to listOf(
        "Category:Featured pictures of objects",
        "Category:Featured pictures of architectural elements",
        "Category:Featured pictures of geology and chemistry",
        "Category:Featured pictures of monetary items",
        "Category:Featured pictures of sculptures",
        "Category:Featured pictures of air transport",
        "Category:Featured pictures of land vehicles",
        "Category:Featured pictures of rail vehicles",
        "Category:Featured pictures of water transport"
    ),
    "checkbox_animals" to listOf(
        "Category:Featured pictures of animals",
        "Category:Featured pictures of amphibians",
        "Category:Featured pictures of arthropods",
        "Category:Featured pictures of Arachnida",
        "Category:Featured pictures of Diptera",
        "Category:Featured pictures of Hymenoptera",
        "Category:Featured pictures of Lepidoptera",
        "Category:Featured pictures of Erebidae",
        "Category:Featured pictures of Hesperiidae",
        "Category:Featured pictures of Lasiocampidae",
        "Category:Featured pictures of Lycaenidae",
        "Category:Featured pictures of Noctuidae",
        "Category:Featured pictures of Nymphalidae",
        "Category:Featured pictures of Papilionidae",
        "Category:Featured pictures of Pieridae",
        "Category:Featured pictures of Riodinidae",
        "Category:Featured pictures of Saturniidae",
        "Category:Featured pictures of Sphingidae",
        "Category:Featured pictures of Odonata",
        "Category:Featured pictures of birds",
        "Category:Featured pictures of Accipitriformes",
        "Category:Featured pictures of Anseriformes",
        "Category:Featured pictures of Charadriiformes",
        "Category:Featured pictures of Coraciiformes",
        "Category:Featured pictures of Passeriformes",
        "Category:Featured pictures of Corvidae",
        "Category:Featured pictures of Fringillidae",
        "Category:Featured pictures of Hirundinidae",
        "Category:Featured pictures of Meliphagidae",
        "Category:Featured pictures of Muscicapidae",
        "Category:Featured pictures of Passerellidae",
        "Category:Featured pictures of Tyrannidae",
        "Category:Featured pictures of Pelecaniformes",
        "Category:Featured pictures of bones and fossils",
        "Category:Featured pictures of bones, shells and fossils",
        "Category:Featured pictures of fish",
        "Category:Featured pictures of animals in their habitats",
        "Category:Featured pictures of mammals",
        "Category:Featured pictures of Artiodactyla",
        "Category:Featured pictures of Carnivora",
        "Category:Featured pictures of primates",
        "Category:Featured pictures of reptiles",
        "Category:Featured pictures of shells"
    ),
    "checkbox_plants" to listOf(
        "Category:Featured pictures of plants",
        "Category:Featured pictures of Asparagales",
        "Category:Featured pictures of Asterales",
        "Category:Featured pictures of Fagales",
        "Category:Featured pictures of Ranunculales",
        "Category:Featured pictures of Rosales"
    ),
    "checkbox_places" to listOf(
        "Category:Featured pictures of places",
        "Category:Featured pictures of agriculture",
        "Category:Featured pictures of architecture",
        "Category:Featured pictures of bridges",
        "Category:Featured pictures of castles and fortifications",
        "Category:Featured pictures of castles and fortifications in Germany",
        "Category:Featured pictures of cityscapes",
        "Category:Featured pictures of cityscapes in the United States",
        "Category:Featured pictures of exteriors",
        "Category:Featured pictures of exteriors in Germany",
        "Category:Featured pictures of palaces",
        "Category:Featured pictures of religious buildings",
        "Category:Featured pictures of towers",
        "Category:Featured pictures of transport",
        "Category:Featured pictures of cemeteries",
        "Category:Featured pictures of industry",
        "Category:Featured pictures of interiors",
        "Category:Featured pictures of interiors of religious buildings",
        "Category:Featured pictures of ceilings of religious buildings",
        "Category:Featured pictures of natural places",
        "Category:Featured pictures of natural places in Australia",
        "Category:Featured pictures of natural places in Austria",
        "Category:Featured pictures of natural places in Canada",
        "Category:Featured pictures of natural places in Chile",
        "Category:Featured pictures of natural places in the Czech Republic",
        "Category:Featured pictures of natural places in Estonia",
        "Category:Featured pictures of natural places in France",
        "Category:Featured pictures of natural places in Germany",
        "Category:Featured pictures of natural places in Iceland",
        "Category:Featured pictures of natural places in India",
        "Category:Featured pictures of natural places in Italy",
        "Category:Featured pictures of natural places in Laos",
        "Category:Featured pictures of natural places in New Zealand",
        "Category:Featured pictures of natural places in Norway",
        "Category:Featured pictures of natural places in Poland",
        "Category:Featured pictures of natural places in Portugal",
        "Category:Featured pictures of natural places in Russia",
        "Category:Featured pictures of natural places in Spain",
        "Category:Featured pictures of natural places in Switzerland",
        "Category:Featured pictures of natural places in Ukraine",
        "Category:Featured pictures of natural places in the United Kingdom",
        "Category:Featured pictures of natural places in the United States",
        "Category:Featured pictures of other places",
        "Category:Featured pictures of panoramas",
        "Category:Featured pictures of roads",
        "Category:Featured pictures of satellite images",
        "Category:Featured pictures of settlements"
    )
)
